### ISSUE TITLE
[issue]: lunr-search doesn't pickup on heading elements that are non-direct children of '.markdown'

### ISSUE THREAD

**Issue by Jeandcc** [praveenn77/docusaurus-lunr-search#115]
Here's a demo codebase used to replicate the issue: https://github.com/Jeandcc/wrapped-heading-issue-w-docusaurus-lunr-search

As you can see [on this file](https://github.com/Jeandcc/wrapped-heading-issue-w-docusaurus-lunr-search/blob/master/src/theme/DocItem/Content/index.js), we [swizzled](https://docusaurus.io/docs/swizzling) the `DocItem` 'component' so we can render some content on the documentation page based on the Front Matter data as well, and not only on the markdown of the page.

``` javascript
// /src/theme/DocItem/Content/index.js
export default function DocItemContent({ children }) {
  const { frontMatter } = useDoc();
  // (...)

  const headingFromFM = frontMatter?.heading || "";
  const descriptionFromFM = frontMatter?.description || "";
  const wrappedHeadingFromFM = frontMatter?.wrappedHeading || "";
  const wrappedDescriptionFromFM = frontMatter?.wrappedDescription || "";

  return (
    <div className={clsx(ThemeClassNames.docs.docMarkdown, "markdown")}>
      { /* (...) */ }

      <MDXContent>
        {headingFromFM && <h2>{headingFromFM}</h2>}
        {descriptionFromFM && <p>{descriptionFromFM}</p>}

        <div>
          {wrappedHeadingFromFM && <h2>{wrappedHeadingFromFM}</h2>}
          {wrappedDescriptionFromFM && <p>{wrappedDescriptionFromFM}</p>}
        </div>

        {children}
      </MDXContent>
    </div>
  );
}
```

[Here's the example doc](https://raw.githubusercontent.com/Jeandcc/wrapped-heading-issue-w-docusaurus-lunr-search/master/docs/lunr-search-issue-demo/index.md) used to render Front Matter content as well as MD content.

The problem that we are currently facing is that **`docusaurus-lunr-search` only pickups the heading elements that are direct children of the `.markdown` element.** Headings that are encapsulated by other elements, such as `divs`, will not get picked up for indexing by `lunr-search`.

# Here's "visual proof":

### Visual preview of the documentation page
![image](https://github.com/praveenn77/docusaurus-lunr-search/assets/47673012/72b35846-657d-4262-bb81-13edde307688)

### Searching for top-level heading generated with FrontMatter and Swizzling:
![image](https://github.com/praveenn77/docusaurus-lunr-search/assets/47673012/d3096575-0e5a-47eb-bc8a-46a7994a23ec)

### Searching for non-top-level heading generated with FrontMatter and Swizzling:
![image](https://github.com/praveenn77/docusaurus-lunr-search/assets/47673012/cb80891c-ce29-4817-ad8a-4a28610ca8a5)

---

After browsing the `docusaurus-lunr-search` codebase, I believe the fix for this issue will touch on these lines of the codebase: https://github.com/praveenn77/docusaurus-lunr-search/blob/44be1f05ec09261399837b3f8a34300de7b8eeaa/src/html-to-doc.js#L109-L118

**Comment by Jeandcc** [comment]
Hello @praveenn77 , any chance you could have a quick look here? I'd be willing to work on a PR if you're too busy, but it would be great to get some insights from you first.

Thanks

**Comment by praveenn77** [comment]
Hi @Jeandcc , thanks for reporting this issue, 
I have made a change and publsihed a new version **_2.4.2_** now you can search your FrontMatter element by adding an attribute `data-search-children` to the wrapper elements.
<img width="730" alt="image" src="https://github.com/praveenn77/docusaurus-lunr-search/assets/20218070/5e7dea81-8d47-4cbc-927d-acf58863914b">
<img width="1171" alt="image" src="https://github.com/praveenn77/docusaurus-lunr-search/assets/20218070/190d1765-4d5f-4b41-a6b2-4fd7ab1ca68b">

Hope this helps,
Thanks.

**Comment by Jeandcc** [comment]
Hi @praveenn77 , thanks a lot for the code you built for this functionality!

I took the freedom to further develop this feature, aiming at reducing the workload for developers in case they have headings on different levels of hierarchy. 

With the previous approach, devs would have to add the `data-search-children` attribute to all divs that contained headings. 

With the PR #117 that I opened, this would not be necessary, as the code would look through all direct and indirect children of the element with the `data-search-children` attribute.

Could you please take a look at it, and let me know in case of questions or requests for tweaks?

Thanks!

**Comment by magraina** [comment]
This worked for me - However I had to add the `className` "anchor" as well as an `id` to the individual heading, to be able to click on  it.
Otherwise the `url`of the link in the search box is something like that `some/url/to-page##` instead of `some/url/to-page#id`
