### ISSUE TITLE
[Feature Request] Highlight matched line after search

### ISSUE THREAD

**Issue by iru2x** [praveenn77/docusaurus-lunr-search#116]
It would be great the ability to highlight the line where your matched word is, to find it quicker.

When you find your matched word, the plugin shows ("escort" you to) the section where the word is, but if the section contains a lot of text, is not easy to find quickly the word you searched.

Would be nicer if, apart from highlight the line, it **bolders** the word or even highlight the word you searched with a stronger color.

**Comment by praveenn77** [comment]
Not able to do line highlight but added a word highlight option in new version v3.0.0 - set `highlightResult` option to `true`

**Comment by iru2x** [comment]
Thanks for hearing the community. Hoping to see that line highlighting in the future, though :smiley:
