### ISSUE TITLE
Support docusaurus 3

### ISSUE THREAD

**Issue by Hinton** [praveenn77/docusaurus-lunr-search#123]
I'm currently in the process of exploring upgrading our docusaurus instance to v3.0.0-rc.1. To do so I've had to override a few of the peer-dependencies in docusaurus-lunr-search.

```json
"docusaurus-lunr-search": {
  "@docusaurus/core":  "$@docusaurus/core",
  "react":  "$react",
  "react-dom":  "$react-dom"
}
``` 

I believe the proper "solution" to this would be to update the package.json to also support `react ^18` and `docusaurus ^3.0.0-rc.1`.

**Comment by praveenn77** [comment]
Thanks for the PR, new version 3.3.0 published
