### ISSUE TITLE
How do I import this search component to use on a custom index/home page?

### ISSUE THREAD

**Issue by alexgurr** [praveenn77/docusaurus-lunr-search#125]
Love the search, but would ideally be able to import it in to my custom home page. Is there any way to do this?

**Comment by praveenn77** [comment]
I don't have any idea that either,
You can try running
`npm run swizzle docusaurus-lunr-search SearchBar -- --eject --danger`
this will copy the search component file to `src/theme/SearchBar`. 
You can make changes to it or try importing it in other pages.
