### ISSUE TITLE
Support for Docusaurus v3

### ISSUE THREAD

**Issue by cmurrayjr** [praveenn77/docusaurus-lunr-search#130]
Opening this Issue to request information on support for Docusaurus v3. 

Edit: [found this PR](https://github.com/praveenn77/docusaurus-lunr-search/pull/124)

Based on the PR above it seems that this is supported 🎉 🎉 

Updating this issue to request information in the readme regarding how to update my lunr-search enabled Docusaurus v2 site to Docusaurus v3. Please include -

* config files that need to be updates 
* commands tha need to be run 
* dependencies or prerequisites that need to take place 

Thanks!

**Comment by praveenn77** [comment]
Updated readme, hope this helps, thanks
https://github.com/praveenn77/docusaurus-lunr-search#upgrading-from-docusaurus-v2-to-v3
