### ISSUE TITLE
Hotkey for opening the search

### ISSUE THREAD

**Issue by Zamiell** [praveenn77/docusaurus-lunr-search#38]
With Algolia, you can press Ctrl+K to handily open the search bar.
With docusaurus-lunr-search, there is no such hotkey available, to my knowledge.

Is this something that can be added? I guess it would just a bit of passive JavaScript that listens for this particular keystroke, and then puts the focus in the search bar.

**Comment by Zamiell** [comment]
In the meantime, this is what I came up with:

hotkey.js
```javascript
// In order for the search box to initialize properly, we have to manually click it
document.addEventListener('DOMContentLoaded', function() {
  const search = document.getElementById('search_input_react');
  search.click();
});

// Ctrl + K should focus the search bar, emulating the Algolia search UI
document.onkeydown = function(e) {
  if (e.ctrlKey && e.key == 'k'){
    const search = document.getElementById('search_input_react');
    search.focus();

    // By default, using Ctrl + K in Chrome will open the location bar, so disable this
    e.preventDefault();
  }
}
```

To enable it, you put it in the `scripts` section of `docusaurus.config.js`.

**Comment by praveenn77** [comment]
Added in new version `3.2.0`
