### ISSUE TITLE
Request for publishing new version

### ISSUE THREAD

**Issue by jknoxville** [praveenn77/docusaurus-lunr-search#78]
Hi there, thanks very much for this plugin, I think it's great!

In docusaurus 2.0.0-beta.5, the isClient API was changed to useIsBrowser ( https://github.com/facebook/docusaurus/commit/295e77cc098790f89e65d6fcd421dc4e3c6d8eac )

Support for this has already been added in this commit: https://github.com/praveenn77/docusaurus-lunr-search/commit/2e1e6036e690b64b9f6413cdd3806cda88e954d2 but this hasn't yet been released to npm.

Please could you create a new release with the current master branch?

Thanks!

**Comment by jjchambl** [comment]
Bump; the lack of a published version with the new API has prevented my org's searches from working correctly.
