### ISSUE TITLE
docusaurus-lunr-search doesn't work after publishing

### ISSUE THREAD

**Issue by RaisaDolci** [praveenn77/docusaurus-lunr-search#80]
The search works in the developer mode but it doesn't after publishing. I figured out that it's a problem with the base url when I used live preview. So I move everything to the same folder (docs) and started live preview again so there was no problem with base url (/docs/). I can't do this on my ftp. Is there any other solution?

**Comment by praveenn77** [comment]
assetUrl option added in new version 3.1.0.
Thanks
