### ISSUE TITLE
Anchor tag does not have correct URL for opening results in a new tab

### ISSUE THREAD

**Issue by evaera** [praveenn77/docusaurus-lunr-search#82]
1. Go to a page within a subfolder, like https://lelouch77.github.io/docusaurus-lunr-search-demo/docs/doc1 on this project's own demo site
2. Search something like "welcome", which will link to the blog section
3. Middle-mouse click it, or look at the browser hover in the bottom left:
![image](https://user-images.githubusercontent.com/2489210/176563460-b50c7505-29dd-48e7-98d6-2cffa97b75bd.png)

The URL is wrong.

Expected: `https://lelouch77.github.io/docusaurus-lunr-search-demo/blog/welcome`
Actual: `https://lelouch77.github.io/docusaurus-lunr-search-demo/docs/blog/welcome`

**Comment by evaera** [comment]
Related issue from my project (which depends on this project) where a user reported this: https://github.com/evaera/moonwave/issues/116

**Comment by efectn** [comment]
Have same issue

**Comment by val1984** [comment]
Having the same issue with latest version of `docusaurus-lunr-search`.

I reverted to `v2.1.15` and it works properly with this version.

**Comment by Lullabyq** [comment]
@val1984, probably you should just update docusaurus to latest version in order to make `docusaurus-lunr-search` work fine with version later than `2.1.15`

**Comment by val1984** [comment]
This is with the latest stable version of Docusaurus: v2.3.1.

**Comment by Lullabyq** [comment]
ok, i have another guess, have you swizzled `DocSearch` component?

_you can check it easily in `src/theme`, DocSearch folder should not be there_

**Comment by val1984** [comment]
@Lullabyq Thank you, I reran [the swizzling command from the docs](https://github.com/praveenn77/docusaurus-lunr-search#how-to-use-) and now the URLs are correct!

**Comment by praveenn77** [comment]
fixed in new version, try `3.1.0`
https://praveenn77.github.io/docusaurus-lunr-search-demo/
