### ISSUE TITLE
Please use SemVer (v2.1.16 breaks v2.1.15-compatible installations)

### ISSUE THREAD

**Issue by e271828-** [praveenn77/docusaurus-lunr-search#84]
Hello,

v2.1.16 broke our setup with some backwards-incompatible indexing changes.

This should more appropriately have been v2.2.0, possibly 3.0.0.

Given a version number MAJOR.MINOR.**PATCH**, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backwards compatible manner
PATCH version when you make **backwards compatible** bug fixes

**Comment by praveenn77** [comment]
I didn't expect it to break backwards compatibility

**Comment by praveenn77** [comment]
Version 2.1.16  is deprecated and 2.2.0 is published
