### ISSUE TITLE
Confusing install instructions in README

### ISSUE THREAD

**Issue by seekayel** [praveenn77/docusaurus-lunr-search#93]
The README provides the following `How to Use` instructions:

1. Install this package
2. Then run `npm install` to update, build, and link the packages
3. Add the docusaurus-lunr-search plugin to your `docusaurus.config.js`
4. Then run docusaurus swizzle
5. Then build your Docusaurus project
6. Serve your application

However, if you skip step 4 everything works fine. If you attempt to edit the files by step 4 they aren't used due to the plugin being loaded from the npm module (step 3).

Question: how to swizzle and customize? Once I swizzle those files don't get used.

Suggestion: make it more clear that swizzling is not needed to use this plugin.

Thanks.

**Comment by AddictArts** [comment]
I can verify swizzling is not needed. Most likely this is suggesting a person might want to customize.

See https://docusaurus.io/docs/swizzling

Once swizzled you wrap it in your `src/` or provide a new implementation as I can tell from reading the docs, but that is not a plugin issue, or this plugins specific thing.

**Comment by zfm-alyssonteixeira** [comment]
So, I'm trying to use this on my docker, I've done local with swizzling (followed all the steps) and worked normally, but now on my docker I'm doing without the swizzle and it's not working, but I don't think the non-swizzling is the problem, is it?

**Comment by praveenn77** [comment]
Read me updated
